# ═══════════════════════════════════════════════════════════════
# Ansible Inventory — AWS EC2
# ⚠️  Update EC2_PUBLIC_IP after running Terraform
# ═══════════════════════════════════════════════════════════════

[app_servers]
# Replace with your EC2 Elastic IP from: terraform output public_ip
34.194.19.44 ansible_user=ubuntu ansible_ssh_private_key_file=/home/bhupesh/devops-main-1/devops_key.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'

[app_servers:vars]
ansible_python_interpreter=/usr/bin/python3
